[workspace]
members = [
    "crates/fyida_app",
    "crates/fyida_analysis",
    "crates/fyida_cli",
    "crates/fyida_core",
    "crates/fyida_disasm",
    "crates/fyida_loader",
    "crates/fyida_ui",
]
resolver = "2"

[workspace.package]
version = "0.22.0-alpha.1"
edition = "2021"
rust-version = "1.77"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
eframe = { version = "0.27.2", default-features = false, features = ["default_fonts", "glow"] }
iced-x86 = "1.21"
msvc-demangler = "0.11"
pdb = "0.8"
rfd = "0.14"
rustc-demangle = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

fyida_analysis = { path = "crates/fyida_analysis" }
fyida_cli = { path = "crates/fyida_cli" }
fyida_core = { path = "crates/fyida_core" }
fyida_disasm = { path = "crates/fyida_disasm" }
fyida_loader = { path = "crates/fyida_loader" }
fyida_ui = { path = "crates/fyida_ui" }
